In [1]:
import load
from plot import plot3D

# from mygp import mygp

import numpy as np
import pandas as pd
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process import kernels
from sklearn.preprocessing import StandardScaler

import skopt 
from skopt.space import Real

from icecream import ic


In [2]:
class mygp(object):

    def __init__(
        self,  
        gp=None,  
        **kwargs    
    ):
    
        if gp:
            self.gp = gp    
        else:
            self.gp = GaussianProcessRegressor()    



        self.ndims=1
        self.sample_X = np.array([])
        self.sample_y = np.array([])

        
        self.kwargs = kwargs
        self.kappa = kwargs.pop("kappa",0.0)
        self.acquisition_function = kwargs.pop("acquisition_function","LCB")    
        self.xi = kwargs.pop("xi", 0.01)     


    def prn(self, **kwargs):


        print(f"ndims = {self.ndims}. sample shape = {self.sample_X.shape}")        
        print(f"kappa={self.kappa}")
        print(f"xi={self.xi}")
        print(f"acquisition_function={self.acquisition_function}")    
        print(self.sample_X)
        print(self.sample_y)   

        return

    def sample_init(self,X,y):

        X_shape = X.shape
        X_len =  len(X_shape)

        
        if X_len == 1:
            self.ndims = 1
        elif X_len == 2:
            self.ndims = X_shape[1]
        else:         
            raise ValueError(f'sample_init() sample_X has incompatiple shape"{X_shape}" for the gaussian fit method.')
        
        self.sample_X = X.copy()
        self.sample_y = y.copy()


        self.gp.fit(self.sample_X, self.sample_y)

        sample_pred , sample_std = self.gp.predict(self.sample_X, return_std=True)

        return sample_pred

    def predict(self, grid_X):
                           
        X_len = len(grid_X.shape)

        if X_len == 1 and self.ndims == 1:
            pass      
        elif X_len ==2 and grid_X.shape[1] == self.ndims:       
            pass        
        else:
            raise ValueError(f'predict() grid_X has shape "{grid_X.shape}" dimensions. ndims = {self.ndims}')   

        grid_pred, grid_std = self.gp.predict(grid_X, return_std=True)

        return grid_pred, grid_std

    def log_marginal_likelihood(self, theta=None,eval_gradient=False, clone_kernel=True):

        return self.gp.log_marginal_likelihood( theta=theta, eval_gradient=eval_gradient,clone_kernel=clone_kernel  )
    
    def get_params(self):
        ic(self.gp.get_params(deep=True))

    def sample_add(self, X1, y1):

        if len(X1) != self.ndims: 
            raise ValueError(f'sample_add(). Error sample_X1 must have exactly "{self.ndims}"')      

        # add point to array
        X = np.concatenate((self.sample_X, [X1]),axis=0 )
        y = np.concatenate((self.sample_y, [y1]),axis=0)     

        # ic(X.shape,y.shape)
        # ic(X,y)
        
        # remember if sucessfull this will update self.sample_X, self.sample_y
        self.sample_init(X,y)

        return
    
    def gp_minimize(self):

        def surrogate_function(inputs):
            # Predict using the Gaussian Process surrogate model
            y_pred, stdev = self.gp.predict(np.atleast_2d(inputs), return_std=True) 
            return y_pred[0]  



        my_domain = [Real(0.0, 1.0, name=f'num_{self.ndims}') for i in range(self.ndims)]    
        
        res = skopt.gp_minimize(
            func=surrogate_function,
            dimensions=my_domain,  # The search space
            # base_estimator= self.gp, 
            acq_func=self.acquisition_function,
            kappa= self.kappa,
            n_calls = 4,  # high to be on the safe side
            
            x0=[list(x) for x in self.sample_X], # Sample X values
            y0= self.sample_y,                   # y target 
            verbose=False                         # debug output ??
        )
        
        print(f"gp_minimize() res.x = {res.x}")
        print(f"gp_minimize() res.fun = {res.fun}")

        suggested = np.array(res.x_iters[-1])
        print("Suggested next inputs to try:", suggested)

        del res  

        return

    def op_minimize(self,X, base_estimator  ):

        if X is None:
            X=np.array([])
         
        values = np.array([])
        my_domain = [Real(0.0, 1.0, name=f'num_{self.ndims}') for i in range(self.ndims)]    

            
        # if self.acquisition_function == "LCB":
        #     acq_func_kwargs = {"kappa": self.kappa}
        # elif self.acquisition_function == "EI" or   self.acquisition_function == "PI":
        #     acq_func_kwargs = {"xi": self.xi}
 
        acq_func_kwargs = {"xi": self.xi, "kappa": self.kappa}      
          
        opt = skopt.Optimizer(
            my_domain,
            base_estimator= self.gp  if base_estimator==None else base_estimator,
            acq_func=self.acquisition_function,
            n_initial_points=1,   
            random_state=0,
            acq_func_kwargs=acq_func_kwargs,
            acq_optimizer='sampling' 
        )
        
        opt.tell(self.sample_X.tolist()   , self.sample_y.tolist(), fit=True)
        possibles = opt.ask()

        # remember opt.models[0] is the base_optimizer in opt
        
        ic(opt.models[0])
        if len(X)>0:
            match self.acquisition_function:
                case "LCB":    
                    values = skopt.acquisition.gaussian_lcb(X, opt.models[0], kappa=self.kappa )    
                case "EI": 
                    values = skopt.acquisition.gaussian_ei(X, opt.models[0], y_opt=np.min(self.sample_y), xi=self.xi )
                case "PI":
                    values = skopt.acquisition.gaussian_pi(X, opt.models[0], y_opt=np.min(self.sample_y), xi=self.xi )    
                case _:
                    raise ValueError(f"op_minimize() unknown acquisition function {self.acquisition_function}") 


        
        # print(f"op_minimize(): value = {values}")         
        # print(f"opt.ask()={possibles}")

        del opt

        return values, possibles
  




In [3]:


def calc(idx, add):
      
    sample_X, sample_y = load.load_function(idx,add, True)
    X_plot = None

    match idx:
          
        case 1:
            # sample_y *= -1.0
            kernel = kernels.Matern(nu=2.5, length_scale=0.01 )
            g = GaussianProcessRegressor(kernel=kernel,n_restarts_optimizer=10)
            gp = mygp(g, kappa=0.0, acquisition_function="LCB", xi=0.01 )
            gp.sample_init(sample_X,sample_y)
            values, possibles = gp.op_minimize(X_plot, None)

        case 2:
            kernel = kernels.Matern(nu=2.5,length_scale=0.01)
            g = GaussianProcessRegressor(kernel=kernel,n_restarts_optimizer=10)
            gp= mygp(g, kappa=0.0, acquisition_function="LCB",xi=0.1 )
            gp.sample_init(sample_X,sample_y)
            values, possibles=gp.op_minimize(X_plot,"GP")

        case 3: 
            # sample_y*=-1.0
            kernel = kernels.Matern(nu=2.5,length_scale=0.01)
            g = GaussianProcessRegressor(kernel=kernel,n_restarts_optimizer=10)
            gp = mygp(g, kappa=0.5, acquisition_function="EI", xi=0.1 )
            gp.sample_init(sample_X,sample_y)
            values, possibles =gp.op_minimize(X_plot, None)

        case 4:
            kernel = kernels.Matern(nu=2.5,length_scale=0.01)
            g = GaussianProcessRegressor(kernel=kernel,n_restarts_optimizer=10)
            gp = mygp(g, kappa=1.0, acquisition_function="EI", xi=0.1)
            gp.sample_init(sample_X,sample_y)
            values, possibles = gp.op_minimize(X_plot, None)          
            
        case 5:
            kernel = kernels.Matern(nu=2.5,length_scale=0.01)
            g = GaussianProcessRegressor(kernel=kernel,n_restarts_optimizer=10)
            gp = mygp(g, kappa=1.0, acquisition_function="LCB", xi=0.1)
            gp.sample_init(sample_X,sample_y)
            values, possibles = gp.op_minimize(X_plot, None)
            
        case 6:
            # sample_y *= -1.0
            kernel = kernels.Matern(nu=2.5,length_scale=0.01)
            g = GaussianProcessRegressor(kernel=kernel,n_restarts_optimizer=10)
            gp= mygp(g, kappa=1.0, acquisition_function="LCB", xi=0.1)
            gp.sample_init(sample_X,sample_y)
            values, possibles = gp.op_minimize(X_plot, None)
        case 7:
            # sample_y *= -1.0    
            kernel = kernels.Matern(nu=2.5,length_scale=0.01)
            g = GaussianProcessRegressor(kernel=kernel,n_restarts_optimizer=10)
            gp = mygp(g, kappa=2.0, acquisition_function="LCB", xi=0.1)
            gp.sample_init(sample_X,sample_y)
            values, possibles = gp.op_minimize(None, "GP")
        case 8: 
            # sample_y *= -1.0
            kernel = kernels.Matern(nu=2.5,length_scale=0.01)
            g = GaussianProcessRegressor(kernel=kernel,n_restarts_optimizer=10)
            gp = mygp(g, kappa=2.0, acquisition_function="EI", xi=0.1)
            gp.sample_init(sample_X,sample_y)
            values, possibles = gp.op_minimize(None, None)

    ic(possibles)    
    if ic.enabled:
        gp.prn()
        
    return possibles


In [5]:



ic.disable()

possibles_list=[]

for idx in range(1,9):
    print(f"idx={idx}")
    possibles=calc(idx,10)
    possibles_list.append(possibles)



load.print_for_capstone (possibles_list)


idx=1
idx=2
idx=3
idx=4
idx=5
idx=6


/home/hmb/anaconda3/envs/ts/lib/python3.10/site-packages/sklearn/gaussian_process/_gpr.py:616: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  _check_optimize_result("lbfgs", opt_res)


idx=7


/home/hmb/anaconda3/envs/ts/lib/python3.10/site-packages/sklearn/gaussian_process/_gpr.py:616: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  _check_optimize_result("lbfgs", opt_res)


idx=8
0.628982-0.470940-
0.184758-0.018406-
0.547907-0.831788-0.460768-
0.791393-0.978545-0.935936-0.820454-
0.081432-0.401261-0.002011-0.798007-
0.001819-0.959575-0.030757-0.019916-0.950110-
0.009317-0.351462-0.541322-0.855039-0.883376-0.565164-
0.975884-0.924846-0.992106-0.273742-0.646718-0.246122-0.899852-0.403664-


/home/hmb/anaconda3/envs/ts/lib/python3.10/site-packages/sklearn/gaussian_process/_gpr.py:616: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  _check_optimize_result("lbfgs", opt_res)


week 10
0.628982-0.470940- <BR>
0.184758-0.018406- <BR>
0.547907-0.831788-0.460768-<BR>
0.791393-0.978545-0.935936-0.820454-<BR>
0.081432-0.401261-0.002011-0.798007-<BR>
0.001819-0.959575-0.030757-0.019916-0.950110-<BR>
0.009317-0.351462-0.541322-0.855039-0.883376-0.565164-<BR>
0.975884-0.924846-0.992106-0.273742-0.646718-0.246122-0.899852-0.403664-<BR>

Week 9 <BR>
0.281711-0.997778-<BR>
0.187256-0.153893-<BR>
0.017902-0.997712-0.776588-<BR>
0.964190-0.932673-0.908234-0.740072-<BR>
0.227669-0.640884-0.777733-0.076647-<BR>
0.147108-0.942920-0.070672-0.083941-0.950822-<BR>
0.194058-0.176859-0.970800-0.379570-0.385568-0.882665-<BR>
0.221161-0.044377-0.185963-0.124843-0.479279-0.734442-0.133208-0.259536-<BR>

0.000546-0.721183- <BR>
0.354506-0.970611- <BR>
0.989766-0.929733-0.995595-<BR>
0.994375-0.955254-0.886629-0.696208-<BR>
0.827452-0.585675-0.151086-0.400371-<BR>
0.001819-0.959575-0.030757-0.019916-0.950110-<BR>
0.289776-0.003340-0.340427-0.253258-0.446117-0.737255-<BR>
0.004768-0.075287-0.324064-0.084006-0.809979-0.791310-0.229669-0.740011-<BR>

In [12]:
ic.enable()
p = calc(5,10)

# a,b = load.load_function(1,10,True)
# print(a)
# print(b)


# ic(a.shape, b.shape)
# ic(a,b)
# print(np.min(b), np.max(b))

ic| X.shape: (20, 4), Xf.shape: (20, 4)
ic| opt.models[0]: GaussianProcessRegressor(kernel=Matern(length_scale=0.01, nu=2.5),
                                            n_restarts_optimizer=10)
ic| possibles: [0.08143183556633805,
                0.4012613851404375,
                0.0020108496758881604,
                0.7980066186495609]


ndims = 4. sample shape = (48, 4)
kappa=1.0
xi=0.1
acquisition_function=LCB
[[0.19144708 0.03819337 0.60741781 0.41458414]
 [0.75865295 0.53651774 0.65600038 0.36034155]
 [0.43834987 0.8043397  0.21024527 0.15129482]
 [0.70605083 0.53419196 0.26424335 0.48208755]
 [0.83647799 0.19360965 0.6638927  0.78564888]
 [0.68343225 0.11866264 0.82904591 0.56757661]
 [0.55362148 0.66734998 0.32380582 0.81486975]
 [0.35235627 0.32224153 0.11697937 0.47311252]
 [0.15378571 0.72938169 0.42259844 0.44307417]
 [0.46344227 0.63002451 0.10790646 0.9576439 ]
 [0.67749115 0.35850951 0.47959222 0.07288048]
 [0.58397341 0.14724265 0.34809746 0.42861465]
 [0.30688872 0.31687813 0.62263448 0.09539906]
 [0.51114177 0.817957   0.72871042 0.11235362]
 [0.43893338 0.77409176 0.37816709 0.93369621]
 [0.22418902 0.84648049 0.87948418 0.87851568]
 [0.72526172 0.47987049 0.08894684 0.75976022]
 [0.35548161 0.63961937 0.41761768 0.12260384]
 [0.11987923 0.86254031 0.64333133 0.84980383]
 [0.12688467 0.15342962 0.77016